# Generated by Django 4.1.4 on 2023-01-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscribed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
