# Generated by Django 4.1.4 on 2023-01-08 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_subscriber_last_name_alter_subscriber_subscribed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='languages',
            new_name='Language',
        ),
    ]
