# Generated by Django 4.1.4 on 2023-04-05 22:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterSubscribers',
            new_name='NewsletterSubscriber',
        ),
    ]
