# Generated by Django 4.1.4 on 2023-04-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_rename_newslettersubscribers_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionstatus',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
