# Generated by Django 4.1.4 on 2023-04-05 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_alter_subscriptionstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionstatus',
            options={'verbose_name_plural': 'Subscription statuses'},
        ),
    ]
