# Generated by Django 4.1.4 on 2023-04-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_newslettersubscriber_newsletter__user_id_81f0b9_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_status', to='newsletter.subscriptionstatus'),
        ),
    ]
