# Generated by Django 4.1.3 on 2023-07-10 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_created', models.DateTimeField(blank=True)),
                ('following_ended', models.DateTimeField(blank=True)),
                ('follower_rank', models.IntegerField()),
                ('Message_number', models.IntegerField()),
                ('last_message', models.DateTimeField()),
                ('battle_wins', models.IntegerField()),
                ('battle_losses', models.IntegerField()),
                ('battle_draws', models.IntegerField()),
                ('last_battle', models.DateTimeField()),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_folling', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='social',
            index=models.Index(fields=['follower_rank'], name='social_soci_followe_0c8330_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('user', 'following')},
        ),
    ]
