export const translations = {
    'English': {
        'Contact': 'Contact',
        'Faq': 'Faq',
        'Privacy': 'Privacy',
        'Terms': 'Terms',
        'Theme': 'Theme',
        'Language': 'Language',
        'Premium': 'Premium',
        'Log in': 'Log in',
    },
    'French': {
        'Contact': 'Contact',
        'Faq': 'Faq',
        'Privacy': 'Confidentialité',
        'Terms': 'Conditions',
        'Theme': 'Thème',
        'Language': 'Langue',
        'Premium': 'Prime',
        'Log in': 'Connexion',
    },
    'Italian': {
        'Contact': 'Contatto',
        'Faq': 'DOMANDE FREQUENTI',
        'Privacy': 'Privacy',
        'Terms': 'Termini e condizioni',
        'Theme': 'Tema',
        'Language': 'Lingua',
        'Premium': 'Premium',
        'Log in': 'Accesso',
    },
    'Portuguese': {
        'Contact': 'Contacto',
        'Faq': 'Faq',
        'Privacy': 'Privacidade',
        'Terms': 'Termos',
        'Theme': 'Tema',
        'Language': 'Língua',
        'Premium': 'Prémio',
        'Log in': 'Iniciar sessão',
    },
    'Spanish': {
        'Contact': 'Contacto',
        'Faq': 'Preguntas Frecuentes',
        'Privacy': 'Privacidad',
        'Terms': 'Términos',
        'Theme': 'Tema',
        'Language': 'Idioma',
        'Premium': 'Premium',
        'Log in': 'Iniciar sesión',
    },
}