export const translations = {
    'English': {
        'Header': 'Conjugat',
        'Subheader': 'Helping you to perfect your verb conjugations',
        'Text1': 'At Conjugat we are here to help you learn verbs and tenses in the order that you will be most likely to encounter them. We use spaced repetition to get you to memorise them.',
        'Text2': 'We have 5 languages to choose from and growing. Perfect any of our growing list of languages to be able to make friends on your travels around the globe.',
        'Text3': 'We have 2000 verbs for each language so that you won\'t mess up your grammar again. Practice the different types of irregular verbs and never make a mistake with them again.',
        'Text4': 'Practice more than verbs - you can practice noun and adjective genders in the same fun way with Conjugat Premium. Let us know what else we should add!',
        'Join now': 'Join now',
    },
    'French': {
        'Header': 'Conjugat',
        'Subheader': 'Nous vous aidons à perfectionner vos conjugaisons de verbes',
        'Text1':'Chez Conjugat, nous sommes là pour vous aider à apprendre les verbes et les temps dans l\'ordre dans lequel vous serez le plus susceptible de les rencontrer. Nous utilisons la répétition espacée pour vous amener à les mémoriser.',
        'Text2':'Nous avons 5 langues à choisir et en croissance. Perfectionnez l\'une de nos listes croissantes de langues pour pouvoir vous faire des amis lors de vos voyages à travers le monde.',
        'Text3':'Nous avons 2000 verbes pour chaque langue afin que vous ne bousilliez plus votre grammaire. Pratiquez les différents types de verbes irréguliers et ne vous trompez plus jamais avec eux.',
        'Text4':'Pratiquez plus que des verbes - vous pouvez pratiquer les genres de noms et d\'adjectifs de la même manière amusante avec Conjugat Premium. Faites-nous savoir ce que nous devrions ajouter d\'autre !',
        'Join now': 'Adhérer maintenant',
    },
    'Italian': {
        'Header': 'Conjugat',
        'Subheader': 'Aiutare a perfezionare le coniugazioni dei verbi',
        'Text1': 'No Conjugat estamos aqui para o ajudar a aprender os verbos e os tempos verbais na ordem em que é mais provável que os encontre. Utilizamos a repetição espaçada para o ajudar a memorizá-los.',
        'Text2': 'Abbiamo 5 lingue tra cui scegliere e in continua crescita. Perfezionate una qualsiasi delle nostre lingue, in continuo aumento, per poter fare amicizia durante i vostri viaggi in tutto il mondo.',
        'Text3': 'Abbiamo 2000 verbi per ogni lingua, in modo da non sbagliare più la grammatica. Esercitatevi con i diversi tipi di verbi irregolari e non sbagliate più.',
        'Text4': 'Esercitatevi non solo con i verbi: con Conjugat Premium potete esercitarvi con i generi dei nomi e degli aggettivi nello stesso modo divertente. Fateci sapere cos\'altro dovremmo aggiungere!',
        'Join now': 'Iscriviti ora',
    },
    'Portuguese': {
        'Header': 'Conjugat',
        'Subheader': 'Ajudá-lo a aperfeiçoar as suas conjugações verbais',
        'Text1': 'No Conjugat estamos aqui para o ajudar a aprender os verbos e os tempos verbais na ordem em que é mais provável que os encontre. Utilizamos a repetição espaçada para o ajudar a memorizá-los.',
        'Text2': 'Temos 5 idiomas à escolha e cada vez mais. Aperfeiçoe qualquer uma da nossa lista crescente de línguas para poder fazer amigos nas suas viagens pelo mundo.',
        'Text3': 'Temos 2000 verbos para cada língua, para que não voltes a fazer asneiras com a tua gramática. Pratica os diferentes tipos de verbos irregulares e nunca mais cometas um erro com eles.',
        'Text4': 'Pratique mais do que verbos - pode praticar géneros de substantivos e adjectivos da mesma forma divertida com o Conjugat Premium. Diga-nos o que mais devemos acrescentar!',
        'Join now': 'Aderir agora',
    },
    'Spanish': {
        'Header': 'Conjugat',
        'Subheader': 'Perfeccionar las conjugaciones verbales',
        'Text1': 'En Conjugat estamos aquí para ayudarte a aprender los verbos y los tiempos verbales en el orden en que es más probable que te los encuentres. Utilizamos la repetición espaciada para que los memorices.',
        'Text2': 'Tenemos 5 idiomas para elegir y seguimos creciendo. Perfecciona cualquiera de nuestra creciente lista de idiomas para poder hacer amigos en tus viajes por todo el mundo.',
        'Text3': 'Tenemos 2000 verbos para cada idioma para que no vuelvas a equivocarte con la gramática. Practica los diferentes tipos de verbos irregulares y no vuelvas a equivocarte con ellos.',
        'Text4': 'Practica algo más que verbos: puedes practicar los géneros sustantivo y adjetivo de la misma forma divertida con Conjugat Premium. ¡Dinos qué más deberíamos añadir!',
        'Join now': 'Inscríbete ahora',
    },
}