# Generated by Django 4.1.4 on 2023-01-17 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_alter_userprofile_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='method_payment', to='subscription.paymentmethod'),
        ),
    ]
