# Generated by Django 4.1.4 on 2023-01-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_rename_languages_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='subscriber',
        ),
    ]
