# Generated by Django 4.1.4 on 2023-01-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romancetense',
            name='tense',
            field=models.CharField(max_length=80),
        ),
    ]
