# Generated by Django 4.1.4 on 2023-01-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0003_alter_romanceconjugation_conjugation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romanceconjugation',
            name='conjugation',
            field=models.CharField(max_length=40),
        ),
    ]
