# Generated by Django 4.1.4 on 2023-01-17 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verbs', '0004_alter_romanceconjugation_conjugation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romancemain',
            name='auxiliary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary_main', to='verbs.romanceauxiliary'),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_progress', to='verbs.language')),
                ('rank', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='rank_progress', to='verbs.romancemain')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
