# Generated by Django 4.1.4 on 2023-01-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0005_alter_romancemain_auxiliary_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='rank',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, related_name='rank_progress', to='verbs.romancemain'),
        ),
    ]
