# Generated by Django 4.1.4 on 2023-04-07 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0007_alter_romancemain_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='RomanceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_group', to='verbs.language')),
            ],
        ),
        migrations.AlterField(
            model_name='romancebase',
            name='base',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='RomanceRhyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases_rhyme_base', to='verbs.romancebase')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_rhyme', to='verbs.language')),
                ('rhymes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases_rhyme', to='verbs.romancebase')),
            ],
        ),
        migrations.CreateModel(
            name='RomanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_model', to='verbs.romancegroup')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_model', to='verbs.language')),
            ],
        ),
        migrations.CreateModel(
            name='RomanceHalfRhyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases_half_rhyme_base', to='verbs.romancebase')),
                ('half_rhymes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases_half_rhyme', to='verbs.romancebase')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_half_rhyme', to='verbs.language')),
            ],
        ),
        migrations.AddIndex(
            model_name='romancerhyme',
            index=models.Index(fields=['rhymes'], name='verbs_roman_rhymes__6ee914_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='romancerhyme',
            unique_together={('language', 'base', 'rhymes')},
        ),
        migrations.AlterUniqueTogether(
            name='romancemodel',
            unique_together={('language', 'model')},
        ),
        migrations.AddIndex(
            model_name='romancehalfrhyme',
            index=models.Index(fields=['half_rhymes'], name='verbs_roman_half_rh_acb9f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='romancehalfrhyme',
            unique_together={('language', 'base', 'half_rhymes')},
        ),
        migrations.AlterUniqueTogether(
            name='romancegroup',
            unique_together={('language', 'group')},
        ),
    ]
