# Generated by Django 4.1.4 on 2023-04-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0008_romancegroup_alter_romancebase_base_romancerhyme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romanceconjugation',
            name='conjugation',
            field=models.CharField(max_length=50),
        ),
    ]
