# Generated by Django 4.1.3 on 2023-04-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0009_alter_romanceconjugation_conjugation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RomanceVerbCassandra',
            fields=[
            ],
        ),
    ]
