# Generated by Django 4.1.3 on 2023-04-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0010_romanceverbcassandra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RomanceVerbCassandra',
            new_name='RomanceTestResult',
        ),
    ]
