# Generated by Django 4.1.3 on 2023-04-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0011_rename_romanceverbcassandra_romancetestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='RomanceTestResult_by_user_and_date',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RomanceTestResult_by_user_and_language',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
    ]
