# Generated by Django 4.1.3 on 2023-04-15 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0012_romancetestresult_by_user_and_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RomanceTestResult_by_user',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
    ]
