# Generated by Django 4.1.3 on 2023-04-17 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0013_romancetestresult_by_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RomanceTestResult_by_user',
        ),
    ]
