# Generated by Django 4.1.3 on 2023-05-30 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Typeface',
        ),
    ]
