# Generated by Django 4.1.3 on 2023-05-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_delete_typeface'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typeface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeface', models.CharField(max_length=20)),
            ],
        ),
    ]
