# Generated by Django 4.1.3 on 2023-05-30 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_typeface'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.CharField(max_length=100)),
                ('typeface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontDB_typeface', to='settings.typeface')),
            ],
        ),
    ]
