# Generated by Django 4.1.3 on 2023-06-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='bodyFont',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_font', to='settings.fontdb'),
        ),
        migrations.AlterField(
            model_name='font',
            name='headerFont',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_font', to='settings.fontdb'),
        ),
    ]
