export const translations = {
    'English': {
        'Title': 'Privacy',
        'Subtitle': 'Please note that this Privacy policy is an extract that was copied from Duolingo',
        'Heading1': 'General',
        'Text1-1': 'At Duolingo, we care about your personal data, so we have prepared this Privacy Policy to explain how we collect, use and share it.',
        'Text1-2': 'This Privacy Policy (“Privacy Policy”) details the personal data Duolingo, Inc. (“Duolingo”, “we”, “us” or “our”) receives about you, how we process it and your rights and obligations in relation to your personal data. Duolingo, Inc., a company registered at 5900 Penn Ave, Second Floor, Pittsburgh, PA 15206, United States of America is the data controller for the purposes of the General Data Protection Regulation (“GDPR”) and any relevant local legislation (“Data Protection Laws”).',
        'Text1-3': 'By using or accessing the Service, you agree to the terms of this Privacy Policy. Capitalized terms not defined here have the meanings set forth in the terms and conditions (the “Terms and Conditions”), located at www.duolingo.com/terms. We may update our Privacy Policy to reflect changes to our information practices. If we do this and the changes are material, we will post a notice that we have made changes to this Privacy Policy on the Website for at least 7 days before the changes are made, and we will indicate the date these terms were last revised at the bottom of the Privacy Policy. Any revisions to this Privacy Policy will become effective at the end of that 7 day period.',
        'Text1-4': 'If you are an employee, worker or contractor of Duolingo, the information about how we handle your personal information is available in the Duolingo internal knowledge base. With respect to employees based in Europe, we are committed to cooperating with European data protection authorities (DPAs) and comply with the advice given by such authorities with regard to human resources data transferred from Europe in the context of the employment relationship.',

        'Heading2': 'Information We Collect',
        'Text2-1': 'This Privacy Policy explains how we collect, use and share your personal data.',
        'Text2-2': 'Information you provide',
        'Text2-3': 'When you use the Service, you will submit information and content to your profile. We will also generate data about your use of our Services including your engagement in educational activities on the Service, or your sending of messages and otherwise transmitting information to other users (“Activity Data”). We also collect technical data about how you interact with our Services; for more information, see Cookies.',
        'Text2-4': 'Activity Data',
        'Text2-5': 'When you use Duolingo in our app or on our website, we use a service named FullStory to log your activity. This provides us with a set of data and a session replay of your activity on Duolingo in the form of a video. FullSory captures and analyzes your usage data to help us make your Duolingo experience better.'
    },
    'French': {
        'Title': 'Confidentialité',
        'Subtitle': 'Veuillez noter que cette politique de confidentialité est un extrait copié de Duolingo',
        'Heading1': 'Général',
        'Text1-1': 'Chez Duolingo, nous nous soucions de vos données personnelles, nous avons donc préparé cette politique de confidentialité pour expliquer comment nous les collectons, les utilisons et les partageons.',
        'Text1-2': 'Cette politique de confidentialité («Politique de confidentialité») détaille les données personnelles que Duolingo, Inc. («Duolingo», «nous», «notre» ou «notre») reçoit à votre sujet, comment nous les traitons et vos droits et obligations par rapport à vos données personnelles. Duolingo, Inc., une société enregistrée au 5900 Penn Ave, Second Floor, Pittsburgh, PA 15206, États-Unis d\'Amérique, est le contrôleur des données aux fins du Règlement général sur la protection des données (« RGPD ») et de toute législation locale pertinente (« Lois sur la protection des données »).',
        'Text1-3': 'En utilisant ou en accédant au Service, vous acceptez les termes de cette Politique de confidentialité. Les termes en majuscules non définis ici ont la signification indiquée dans les termes et conditions (les « Termes et Conditions »), situés sur www.duolingo.com/terms. Nous pouvons mettre à jour notre politique de confidentialité pour refléter les modifications apportées à nos pratiques en matière d\'informations. Si nous le faisons et que les modifications sont importantes, nous publierons un avis indiquant que nous avons apporté des modifications à cette politique de confidentialité sur le site Web pendant au moins 7 jours avant que les modifications ne soient apportées, et nous indiquerons la date à laquelle ces conditions ont été révisées pour la dernière fois à au bas de la politique de confidentialité. Toute révision de cette politique de confidentialité entrera en vigueur à la fin de cette période de 7 jours.',
        'Text1-4': 'Si vous êtes un employé, un ouvrier ou un sous-traitant de Duolingo, les informations sur la manière dont nous traitons vos informations personnelles sont disponibles dans la base de connaissances interne de Duolingo. En ce qui concerne les employés basés en Europe, nous nous engageons à coopérer avec les autorités européennes de protection des données (DPA) et à respecter les conseils donnés par ces autorités concernant les données de ressources humaines transférées depuis l\'Europe dans le cadre de la relation de travail.',

        'Heading2': 'Informations que nous recueillons',
        'Text2-2Text2-1': 'Cette politique de confidentialité explique comment nous collectons, utilisons et partageons vos données personnelles.',
        'Text2-2': 'Informations que vous fournissez',
        'Text2-3': 'Lorsque vous utilisez le Service, vous soumettez des informations et du contenu à votre profil. Nous générerons également des données sur votre utilisation de nos Services, y compris votre engagement dans des activités éducatives sur le Service, ou votre envoi de messages et toute autre transmission d\'informations à d\'autres utilisateurs ("Données d\'activité"). Nous recueillons également des données techniques sur la façon dont vous interagissez avec nos Services ; pour plus d\'informations, voir Cookies.',
        'Text2-4': 'Données d\'activité',
        'Text2-5': 'Lorsque vous utilisez Duolingo dans notre application ou sur notre site Web, nous utilisons un service nommé FullStory pour enregistrer votre activité. Celui-ci nous fournit un ensemble de données et un replay de session de votre activité sur Duolingo sous forme de vidéo. FullSory capture et analyse vos données d\'utilisation pour nous aider à améliorer votre expérience Duolingo.'

    }
}