export const translations = {
    'English': {
        'Title1': 'Activate account',
        'Title2': 'Account activation failed',
        'metaContent1': '',
        'metaContent2': '',
        'Text1': 'You have successfully activated your account.',
        'Text2': 'Something went wrong. Please try again later.',
        'Login': 'Login',
    },
    'French': {
        'Title1': 'Activer le compte',
        'Title2': 'Account activation failed',
        'metaContent1': '',
        'metaContent2': '',
        'Text1': 'Vous avez activé votre compte avec succès.',
        'Text2': 'Un problème s\'est produit. Veuillez réessayer plus tard.',
        'Login': 'Connexion',
    },
    'Italian': {
        'Title1': 'Attivare l\'account',
        'Title2': 'Attivazione dell\'account non riuscita',
        'metaContent1': '',
        'metaContent2': '',
        'Text1': 'L\'attivazione dell\'account è avvenuta con successo.',
        'Text2': 'Qualcosa è andato storto. Riprovare più tardi.',
        'Login': 'Accesso',
    },
    'Portuguese': {
        'Title1': 'Activar a conta',
        'Title2': 'A activação da conta falhou',
        'metaContent1': '',
        'metaContent2': '',
        'Text1': 'A sua conta foi activada com sucesso.',
        'Text2': 'Algo correu mal. Por favor, tente novamente mais tarde.',
        'Login': 'Iniciar sessão',
    },
    'Spanish': {
        'Title1': 'Activar cuenta',
        'Title2': 'Error en la activación de la cuenta',
        'metaContent1': '',
        'metaContent2': '',
        'Text1': 'Ha activado correctamente su cuenta.',
        'Text2': 'Algo ha ido mal. Vuelva a intentarlo más tarde.',
        'Login': 'Inicio de sesión',
    }
}