# Generated by Django 4.1.4 on 2023-01-16 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RomanceBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=20)),
                ('rank', models.PositiveIntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_base', to='verbs.language')),
            ],
        ),
        migrations.CreateModel(
            name='RomanceConjugation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conjugation', models.CharField(max_length=20)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='verbs.romancebase')),
            ],
        ),
        migrations.CreateModel(
            name='RomanceTense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_tense', to='verbs.language')),
            ],
        ),
        migrations.CreateModel(
            name='RomanceSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_subject', to='verbs.language')),
            ],
        ),
        migrations.CreateModel(
            name='RomanceMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('auxiliary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary_main', to='verbs.romancetense')),
                ('conjugation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjugation_main', to='verbs.romanceconjugation')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_main', to='verbs.romancesubject')),
                ('tense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tense_main', to='verbs.romancetense')),
            ],
            options={
                'verbose_name_plural': 'Romance main',
            },
        ),
        migrations.CreateModel(
            name='RomanceAuxiliary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxiliary', models.CharField(blank=True, max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_auxiliary', to='verbs.language')),
            ],
            options={
                'verbose_name_plural': 'Romance auxiliaries',
            },
        ),
        migrations.AddIndex(
            model_name='romancetense',
            index=models.Index(fields=['tense'], name='verbs_roman_tense_7d1c78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='romancetense',
            unique_together={('tense', 'language')},
        ),
        migrations.AddIndex(
            model_name='romancesubject',
            index=models.Index(fields=['subject'], name='verbs_roman_subject_ecf00c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='romancesubject',
            unique_together={('subject', 'language')},
        ),
        migrations.AddIndex(
            model_name='romancemain',
            index=models.Index(fields=['auxiliary'], name='verbs_roman_auxilia_35edde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='romancemain',
            unique_together={('subject', 'auxiliary', 'conjugation')},
        ),
        migrations.AddIndex(
            model_name='romanceconjugation',
            index=models.Index(fields=['conjugation'], name='verbs_roman_conjuga_f7ef1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='romanceconjugation',
            unique_together={('base', 'conjugation')},
        ),
        migrations.AddIndex(
            model_name='romancebase',
            index=models.Index(fields=['base'], name='verbs_roman_base_90b659_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='romancebase',
            unique_together={('language', 'base'), ('language', 'rank')},
        ),
        migrations.AddIndex(
            model_name='romanceauxiliary',
            index=models.Index(fields=['auxiliary'], name='verbs_roman_auxilia_fa3b22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='romanceauxiliary',
            unique_together={('auxiliary', 'language')},
        ),
    ]
