# Generated by Django 4.1.4 on 2023-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0006_alter_progress_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romancemain',
            name='rank',
            field=models.PositiveIntegerField(),
        ),
    ]
